# Generated by Django 3.2 on 2023-01-05 18:41

from django.db import migrations, models
try:
    from django.db.models import JSONField
except ImportError:
    try:
        from jsonfield.fields import JSONField
    except ImportError:
        raise ImportError("Can't find a JSONField implementation, please install jsonfield if django < 4.0")

class Migration(migrations.Migration):

    dependencies = [
        ('ModelTracker', '0003_history_related_objects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='new_state',
            field=JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='history',
            name='old_state',
            field=JSONField(default=dict),
        ),
    ]
