# Generated by Django 3.2 on 2023-01-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelTracker', '0003_history_related_objects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='new_state',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='history',
            name='old_state',
            field=models.JSONField(default=dict),
        ),
    ]
