# Generated by Django 2.2.19 on 2024-07-29 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModelTracker', '0004_auto_20230105_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='old_state',
        ),
    ]
